### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by lc1294** [yapyeeqiang/whatsapp-sender#2]
Dependency issue , even after installing requirements from requirements.txt.

Error output as of bellow:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (4.0.0) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

Traceback (most recent call last):
  File "app.py", line 5, in <module>
from utils.whatsapp import send_message
  File "/home/linuschin/Documents/whatsapp-sender-master/utils/whatsapp.py", line 6, in <module> 
from termcolor import colored

ModuleNotFoundError: No module named 'termcolor' 
```

**Comment by yapyeeqiang** [comment]
@lc1294, this issue should be fixed. There's some issue with the package `termcolor` . I removed the usage of the package. No big issue 👍 .
